doctrine:
  dbal:
    driver: pdo_mysql
    host: 127.0.0.1  # Nombre del servicio del contenedor Docker MySQL
    port: 3306  # Puerto por defecto de MySQL
    dbname: test  # Nombre de la base de datos
    user: root  # Usuario de la base de datos
    password:   # Contraseña de la base de datos
    charset: utf8mb4  # Caracteres para admitir emojis, etc. (puede variar según tus necesidades)

  orm:
    mappings:
      App:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App